# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "hashicorp/precise64"
  config.vm.provider "ansible" do |v|
    v.name = "Ansible"
  end
  config.vm.provision "ansible" do |a|
   a.playbook = "playbook.yml"
  end
end
